### PR TITLE
Update catalog-info file with correct system property

### PR DESCRIPTION
**Pull request by ev1yehor**
Relates: https://github.com/elastic/ingest-dev/issues/3398

### CODE REVIEW

**Review by pierrehilbert — APPROVED** [review]

**Comment by jlind23** [comment]
Looks like the process step failed so I retried it.

**Review by jlind23 — APPROVED** [review]

**Comment by oakrizan** [comment]
test

**Comment by rowlandgeoff** [comment]
Ok to merge since Olga opened a follow-up issue

**Pull request merged**
